//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradingBookProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Users : DataEntity
    {
        public Users()
        {
            this.GroupDetails = new HashSet<GroupDetails>();
            this.Groups = new HashSet<Groups>();
            this.SubjectDetails = new HashSet<SubjectDetails>();
            this.Years = new HashSet<Years>();
        }
    
        public string username { get; set; }
        public string passwd { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<GroupDetails> GroupDetails { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual ICollection<SubjectDetails> SubjectDetails { get; set; }
        public virtual ICollection<Years> Years { get; set; }
    }
}
