//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace GradingBookProject.Models
{
    /// <summary>
    /// User's class
    /// </summary>
    public partial class Users
    {
        public Users()
        {
            this.Years = new HashSet<Years>();
        }
    
        /// <summary>
        /// User id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// User's name (login)
        /// </summary>
        public string username { get; set; }
        /// <summary>
        /// User's password
        /// </summary>
        public string passwd { get; set; }
        /// <summary>
        /// User's email
        /// </summary>
        public string email { get; set; }
        /// <summary>
        /// User's name
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// User's surname
        /// </summary>
        public string surname { get; set; }
    
        public virtual ICollection<Years> Years { get; set; }
    }
}
