//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradingBookProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public Grades()
        {
            this.Subjects = new HashSet<Subjects>();
        }
    
        public int id { get; set; }
        public string value { get; set; }
    
        public virtual ICollection<Subjects> Subjects { get; set; }
    }
}
