//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradingBookProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// Subject class
    /// </summary>
    public partial class Subjects
    {
        public Subjects()
        {
            this.SubjectDetails = new HashSet<SubjectDetails>();
        }
    
        /// <summary>
        /// Subject id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// Name of the subject
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// Description of the subject
        /// </summary>
        public string sub_desc { get; set; }
        /// <summary>
        /// Year id in which subject is
        /// </summary>
        [Required]
        public int year_id { get; set; }
        /// <summary>
        /// Mail to the teacher who conducts classes
        /// </summary>
        public string teacher_mail { get; set; }
        /// <summary>
        /// Set of grades
        /// </summary>
        public virtual ICollection<SubjectDetails> SubjectDetails { get; set; }
        public virtual Years Years { get; set; }
    }
}
