//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradingBookProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Years
    {
        public Years()
        {
            this.Users = new HashSet<Users>();
            this.Subjects = new HashSet<Subjects>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public DateTime start { get; set; }
        public DateTime end_date { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Subjects> Subjects { get; set; }
    }
}
